package org.ton.asm

import org.ton.asm.stackbasic.*
import org.ton.asm.stackcomplex.*
import org.ton.asm.tuple.*
import org.ton.asm.constint.*
import org.ton.asm.constdata.*
import org.ton.asm.arithmbasic.*
import org.ton.asm.arithmdiv.*
import org.ton.asm.arithmlogical.*
import org.ton.asm.arithmquiet.*
import org.ton.asm.compareint.*
import org.ton.asm.compareother.*
import org.ton.asm.cellbuild.*
import org.ton.asm.cellparse.*
import org.ton.asm.contbasic.*
import org.ton.asm.contconditional.*
import org.ton.asm.contloops.*
import org.ton.asm.contstack.*
import org.ton.asm.contcreate.*
import org.ton.asm.contregisters.*
import org.ton.asm.contdict.*
import org.ton.asm.exceptions.*
import org.ton.asm.dictcreate.*
import org.ton.asm.dictserial.*
import org.ton.asm.dictget.*
import org.ton.asm.dictset.*
import org.ton.asm.dictsetbuilder.*
import org.ton.asm.dictdelete.*
import org.ton.asm.dictmayberef.*
import org.ton.asm.dictprefix.*
import org.ton.asm.dictnext.*
import org.ton.asm.dictmin.*
import org.ton.asm.dictspecial.*
import org.ton.asm.dictsub.*
import org.ton.asm.appgas.*
import org.ton.asm.apprnd.*
import org.ton.asm.appconfig.*
import org.ton.asm.appglobal.*
import org.ton.asm.appcrypto.*
import org.ton.asm.appmisc.*
import org.ton.asm.appcurrency.*
import org.ton.asm.appaddr.*
import org.ton.asm.appactions.*
import org.ton.asm.debug.*
import org.ton.asm.codepage.*
import org.ton.tlb.TlbCombinator
import org.ton.tlb.TlbConstructor
import org.ton.tlb.providers.TlbCombinatorProvider
import org.ton.tlb.providers.TlbConstructorProvider

interface AsmInstruction {
    companion object : TlbCombinatorProvider<AsmInstruction> by AsmInstructionTlbCombinator
}

private object AsmInstructionTlbCombinator : TlbCombinator<AsmInstruction>() {
    override val constructors: List<TlbConstructor<out AsmInstruction>> = tlbConstructors(
        NOP,
        SWAP,
        XCHG_0I,
        XCHG_IJ,
        XCHG_0I_LONG,
        XCHG_1I,
        PUSH,
        DUP,
        OVER,
        POP,
        DROP,
        NIP,
        XCHG3,
        XCHG2,
        XCPU,
        PUXC,
        PUSH2,
        XCHG3_ALT,
        XC2PU,
        XCPUXC,
        XCPU2,
        PUXC2,
        PUXCPU,
        PU2XC,
        PUSH3,
        BLKSWAP,
        ROT2,
        ROLL,
        ROLLREV,
        PUSH_LONG,
        POP_LONG,
        ROT,
        ROTREV,
        SWAP2,
        DROP2,
        DUP2,
        OVER2,
        REVERSE,
        BLKDROP,
        BLKPUSH,
        PICK,
        ROLLX,
        ROLLREVX,
        BLKSWX,
        REVX,
        DROPX,
        TUCK,
        XCHGX,
        DEPTH,
        CHKDEPTH,
        ONLYTOPX,
        ONLYX,
        BLKDROP2,
        NULL,
        ISNULL,
        TUPLE,
        NIL,
        SINGLE,
        PAIR,
        TRIPLE,
        INDEX,
        FIRST,
        SECOND,
        THIRD,
        UNTUPLE,
        UNSINGLE,
        UNPAIR,
        UNTRIPLE,
        UNPACKFIRST,
        CHKTUPLE,
        EXPLODE,
        SETINDEX,
        SETFIRST,
        SETSECOND,
        SETTHIRD,
        INDEXQ,
        FIRSTQ,
        SECONDQ,
        THIRDQ,
        SETINDEXQ,
        SETFIRSTQ,
        SETSECONDQ,
        SETTHIRDQ,
        TUPLEVAR,
        INDEXVAR,
        UNTUPLEVAR,
        UNPACKFIRSTVAR,
        EXPLODEVAR,
        SETINDEXVAR,
        INDEXVARQ,
        SETINDEXVARQ,
        TLEN,
        QTLEN,
        ISTUPLE,
        LAST,
        TPUSH,
        TPOP,
        NULLSWAPIF,
        NULLSWAPIFNOT,
        NULLROTRIF,
        NULLROTRIFNOT,
        NULLSWAPIF2,
        NULLSWAPIFNOT2,
        NULLROTRIF2,
        NULLROTRIFNOT2,
        INDEX2,
        CADR,
        CDDR,
        INDEX3,
        CADDR,
        CDDDR,
        PUSHINT_4,
        ZERO,
        ONE,
        TWO,
        TEN,
        TRUE,
        PUSHINT_8,
        PUSHINT_16,
        PUSHINT_LONG,
        PUSHPOW2,
        PUSHNAN,
        PUSHPOW2DEC,
        PUSHNEGPOW2,
        PUSHREF,
        PUSHREFSLICE,
        PUSHREFCONT,
        PUSHSLICE,
        PUSHSLICE_REFS,
        PUSHSLICE_LONG,
        PUSHCONT,
        PUSHCONT_SHORT,
        ADD,
        SUB,
        SUBR,
        NEGATE,
        INC,
        DEC,
        ADDCONST,
        MULCONST,
        MUL,
        DIV_BASE,
        DIV,
        DIVR,
        DIVC,
        MOD,
        DIVMOD,
        DIVMODR,
        DIVMODC,
        RSHIFTR_VAR,
        RSHIFTC_VAR,
        RSHIFTR,
        RSHIFTC,
        MODPOW2,
        MULDIV,
        MULDIVR,
        MULDIVMOD,
        MULRSHIFT_VAR,
        MULRSHIFTR_VAR,
        MULRSHIFTC_VAR,
        MULRSHIFT,
        MULRSHIFTR,
        MULRSHIFTC,
        LSHIFTDIV_VAR,
        LSHIFTDIVR_VAR,
        LSHIFTDIVC_VAR,
        LSHIFTDIV,
        LSHIFTDIVR,
        LSHIFTDIVC,
        LSHIFT,
        RSHIFT,
        LSHIFT_VAR,
        RSHIFT_VAR,
        POW2,
        AND,
        OR,
        XOR,
        NOT,
        FITS,
        CHKBOOL,
        UFITS,
        CHKBIT,
        FITSX,
        UFITSX,
        BITSIZE,
        UBITSIZE,
        MIN,
        MAX,
        MINMAX,
        ABS,
        QADD,
        QSUB,
        QSUBR,
        QNEGATE,
        QINC,
        QDEC,
        QMUL,
        QDIV,
        QDIVR,
        QDIVC,
        QMOD,
        QDIVMOD,
        QDIVMODR,
        QDIVMODC,
        QMULDIVR,
        QMULDIVMOD,
        QLSHIFT,
        QRSHIFT,
        QPOW2,
        QAND,
        QOR,
        QXOR,
        QNOT,
        QFITS,
        QUFITS,
        QFITSX,
        QUFITSX,
        SGN,
        LESS,
        EQUAL,
        LEQ,
        GREATER,
        NEQ,
        GEQ,
        CMP,
        EQINT,
        ISZERO,
        LESSINT,
        ISNEG,
        ISNPOS,
        GTINT,
        ISPOS,
        ISNNEG,
        NEQINT,
        ISNAN,
        CHKNAN,
        SEMPTY,
        SDEMPTY,
        SREMPTY,
        SDFIRST,
        SDLEXCMP,
        SDEQ,
        SDPFX,
        SDPFXREV,
        SDPPFX,
        SDPPFXREV,
        SDSFX,
        SDSFXREV,
        SDPSFX,
        SDPSFXREV,
        SDCNTLEAD0,
        SDCNTLEAD1,
        SDCNTTRAIL0,
        SDCNTTRAIL1,
        NEWC,
        ENDC,
        STI,
        STU,
        STREF,
        STBREFR,
        STSLICE,
        STIX,
        STUX,
        STIXR,
        STUXR,
        STIXQ,
        STUXQ,
        STIXRQ,
        STUXRQ,
        STI_ALT,
        STU_ALT,
        STIR,
        STUR,
        STIQ,
        STUQ,
        STIRQ,
        STURQ,
        STREF_ALT,
        STBREF,
        STSLICE_ALT,
        STB,
        STREFR,
        STBREFR_ALT,
        STSLICER,
        STBR,
        STREFQ,
        STBREFQ,
        STSLICEQ,
        STBQ,
        STREFRQ,
        STBREFRQ,
        STSLICERQ,
        STBRQ,
//        STREFCONST,
//        STREF2CONST,
        ENDXC,
        STILE4,
        STULE4,
        STILE8,
        STULE8,
        BDEPTH,
        BBITS,
        BREFS,
        BBITREFS,
        BREMBITS,
        BREMREFS,
        BREMBITREFS,
        BCHKBITS,
        BCHKBITS_VAR,
        BCHKREFS,
        BCHKBITREFS,
        BCHKBITSQ,
        BCHKBITSQ_VAR,
        BCHKREFSQ,
        BCHKBITREFSQ,
        STZEROES,
        STONES,
        STSAME,
//        STSLICECONST,
        STZERO,
        STONE,
        CTOS,
        ENDS,
        LDI,
        LDU,
        LDREF,
        LDREFRTOS,
        LDSLICE,
        LDIX,
        LDUX,
        PLDIX,
        PLDUX,
        LDIXQ,
        LDUXQ,
        PLDIXQ,
        PLDUXQ,
        LDI_ALT,
        LDU_ALT,
        PLDI,
        PLDU,
        LDIQ,
        LDUQ,
        PLDIQ,
        PLDUQ,
        PLDUZ,
        LDSLICEX,
        PLDSLICEX,
        LDSLICEXQ,
        PLDSLICEXQ,
        LDSLICE_ALT,
        PLDSLICE,
        LDSLICEQ,
        PLDSLICEQ,
        SDCUTFIRST,
        SDSKIPFIRST,
        SDCUTLAST,
        SDSKIPLAST,
        SDSUBSTR,
        SDBEGINSX,
        SDBEGINSXQ,
//        SDBEGINS,
//        SDBEGINSQ,
        SCUTFIRST,
        SSKIPFIRST,
        SCUTLAST,
        SSKIPLAST,
        SUBSLICE,
        SPLIT,
        SPLITQ,
        XCTOS,
        XLOAD,
        XLOADQ,
        SCHKBITS,
        SCHKREFS,
        SCHKBITREFS,
        SCHKBITSQ,
        SCHKREFSQ,
        SCHKBITREFSQ,
        PLDREFVAR,
        SBITS,
        SREFS,
        SBITREFS,
        PLDREFIDX,
        PLDREF,
        LDILE4,
        LDULE4,
        LDILE8,
        LDULE8,
        PLDILE4,
        PLDULE4,
        PLDILE8,
        PLDULE8,
        LDILE4Q,
        LDULE4Q,
        LDILE8Q,
        LDULE8Q,
        PLDILE4Q,
        PLDULE4Q,
        PLDILE8Q,
        PLDULE8Q,
        LDZEROES,
        LDONES,
        LDSAME,
        SDEPTH,
        CDEPTH,
        EXECUTE,
        JMPX,
        CALLXARGS,
        CALLXARGS_VAR,
        JMPXARGS,
        RETARGS,
        RET,
        RETALT,
        BRANCH,
        CALLCC,
        JMPXDATA,
        CALLCCARGS,
        CALLXVARARGS,
        RETVARARGS,
        JMPXVARARGS,
        CALLCCVARARGS,
//        CALLREF,
//        JMPREF,
//        JMPREFDATA,
        RETDATA,
        IFRET,
        IFNOTRET,
        IF,
        IFNOT,
        IFJMP,
        IFNOTJMP,
        IFELSE,
//        IFREF,
//        IFNOTREF,
//        IFJMPREF,
//        IFNOTJMPREF,
        CONDSEL,
        CONDSELCHK,
        IFRETALT,
        IFNOTRETALT,
//        IFREFELSE,
//        IFELSEREF,
//        IFREFELSEREF,
        IFBITJMP,
        IFNBITJMP,
//        IFBITJMPREF,
//        IFNBITJMPREF,
        REPEAT,
        REPEATEND,
        UNTIL,
        UNTILEND,
        WHILE,
        WHILEEND,
        AGAIN,
        AGAINEND,
        REPEATBRK,
        REPEATENDBRK,
        UNTILBRK,
        UNTILENDBRK,
        WHILEBRK,
        WHILEENDBRK,
        AGAINBRK,
        AGAINENDBRK,
//        SETCONTARGS_N,
//        SETNUMARGS,
//        SETCONTARGS,
        RETURNARGS,
        RETURNVARARGS,
        SETCONTVARARGS,
        SETNUMVARARGS,
        BLESS,
        BLESSVARARGS,
        BLESSARGS,
        BLESSNUMARGS,
        PUSHCTR,
        PUSHROOT,
        POPCTR,
        POPROOT,
        SETCONTCTR,
        SETRETCTR,
        SETALTCTR,
        POPSAVE,
        SAVE,
        SAVEALT,
        SAVEBOTH,
        PUSHCTRX,
        POPCTRX,
        SETCONTCTRX,
        COMPOS,
        COMPOSALT,
        COMPOSBOTH,
        ATEXIT,
        ATEXITALT,
        SETEXITALT,
        THENRET,
        THENRETALT,
        INVERT,
        BOOLEVAL,
        SAMEALT,
        SAMEALTSAVE,
        CALLDICT,
        CALLDICT_LONG,
        JMPDICT,
        PREPAREDICT,
        THROW_SHORT,
        THROWIF_SHORT,
        THROWIFNOT_SHORT,
        THROW,
        THROWARG,
        THROWIF,
        THROWARGIF,
        THROWIFNOT,
        THROWARGIFNOT,
        THROWANY,
        THROWARGANY,
        THROWANYIF,
        THROWARGANYIF,
        THROWANYIFNOT,
        THROWARGANYIFNOT,
        TRY,
        TRYARGS,
        NEWDICT,
        DICTEMPTY,
        STDICTS,
        STDICT,
        SKIPDICT,
        LDDICTS,
        PLDDICTS,
        LDDICT,
        PLDDICT,
        LDDICTQ,
        PLDDICTQ,
        DICTGET,
        DICTGETREF,
        DICTIGET,
        DICTIGETREF,
        DICTUGET,
        DICTUGETREF,
        DICTSET,
        DICTSETREF,
        DICTISET,
        DICTISETREF,
        DICTUSET,
        DICTUSETREF,
        DICTSETGET,
        DICTSETGETREF,
        DICTISETGET,
        DICTISETGETREF,
        DICTUSETGET,
        DICTUSETGETREF,
        DICTREPLACE,
        DICTREPLACEREF,
        DICTIREPLACE,
        DICTIREPLACEREF,
        DICTUREPLACE,
        DICTUREPLACEREF,
        DICTREPLACEGET,
        DICTREPLACEGETREF,
        DICTIREPLACEGET,
        DICTIREPLACEGETREF,
        DICTUREPLACEGET,
        DICTUREPLACEGETREF,
        DICTADD,
        DICTADDREF,
        DICTIADD,
        DICTIADDREF,
        DICTUADD,
        DICTUADDREF,
        DICTADDGET,
        DICTADDGETREF,
        DICTIADDGET,
        DICTIADDGETREF,
        DICTUADDGET,
        DICTUADDGETREF,
        DICTSETB,
        DICTISETB,
        DICTUSETB,
        DICTSETGETB,
        DICTISETGETB,
        DICTUSETGETB,
        DICTREPLACEB,
        DICTIREPLACEB,
        DICTUREPLACEB,
        DICTREPLACEGETB,
        DICTIREPLACEGETB,
        DICTUREPLACEGETB,
        DICTADDB,
        DICTIADDB,
        DICTUADDB,
        DICTADDGETB,
        DICTIADDGETB,
        DICTUADDGETB,
        DICTDEL,
        DICTIDEL,
        DICTUDEL,
        DICTDELGET,
        DICTDELGETREF,
        DICTIDELGET,
        DICTIDELGETREF,
        DICTUDELGET,
        DICTUDELGETREF,
        DICTGETOPTREF,
        DICTIGETOPTREF,
        DICTUGETOPTREF,
        DICTSETGETOPTREF,
        DICTISETGETOPTREF,
        DICTUSETGETOPTREF,
        PFXDICTSET,
        PFXDICTREPLACE,
        PFXDICTADD,
        PFXDICTDEL,
        DICTGETNEXT,
        DICTGETNEXTEQ,
        DICTGETPREV,
        DICTGETPREVEQ,
        DICTIGETNEXT,
        DICTIGETNEXTEQ,
        DICTIGETPREV,
        DICTIGETPREVEQ,
        DICTUGETNEXT,
        DICTUGETNEXTEQ,
        DICTUGETPREV,
        DICTUGETPREVEQ,
        DICTMIN,
        DICTMINREF,
        DICTIMIN,
        DICTIMINREF,
        DICTUMIN,
        DICTUMINREF,
        DICTMAX,
        DICTMAXREF,
        DICTIMAX,
        DICTIMAXREF,
        DICTUMAX,
        DICTUMAXREF,
        DICTREMMIN,
        DICTREMMINREF,
        DICTIREMMIN,
        DICTIREMMINREF,
        DICTUREMMIN,
        DICTUREMMINREF,
        DICTREMMAX,
        DICTREMMAXREF,
        DICTIREMMAX,
        DICTIREMMAXREF,
        DICTUREMMAX,
        DICTUREMMAXREF,
        DICTIGETJMP,
        DICTUGETJMP,
        DICTIGETEXEC,
        DICTUGETEXEC,
//        DICTPUSHCONST,
        PFXDICTGETQ,
        PFXDICTGET,
        PFXDICTGETJMP,
        PFXDICTGETEXEC,
//        PFXDICTCONSTGETJMP,
        DICTIGETJMPZ,
        DICTUGETJMPZ,
        DICTIGETEXECZ,
        DICTUGETEXECZ,
        SUBDICTGET,
        SUBDICTIGET,
        SUBDICTUGET,
        SUBDICTRPGET,
        SUBDICTIRPGET,
        SUBDICTURPGET,
        ACCEPT,
        SETGASLIMIT,
        COMMIT,
        RANDU256,
        RAND,
        SETRAND,
        ADDRAND,
        GETPARAM,
        NOW,
        BLOCKLT,
        LTIME,
        RANDSEED,
        BALANCE,
        MYADDR,
        CONFIGROOT,
        CONFIGDICT,
        CONFIGPARAM,
        CONFIGOPTPARAM,
        GETGLOBVAR,
//        GETGLOB,
        SETGLOBVAR,
//        SETGLOB,
        HASHCU,
        HASHSU,
        SHA256U,
        CHKSIGNU,
        CHKSIGNS,
        CDATASIZEQ,
        CDATASIZE,
        SDATASIZEQ,
        SDATASIZE,
        LDGRAMS,
        LDVARINT16,
        STGRAMS,
        STVARINT16,
        LDMSGADDR,
        LDMSGADDRQ,
        PARSEMSGADDR,
        PARSEMSGADDRQ,
        REWRITESTDADDR,
        REWRITESTDADDRQ,
        REWRITEVARADDR,
        REWRITEVARADDRQ,
        SENDRAWMSG,
        RAWRESERVE,
        RAWRESERVEX,
        SETCODE,
        SETLIBCODE,
        CHANGELIB,
//        DEBUG,
//        DEBUGSTR,
        DUMPSTK,
        DUMP,
//        SETCP,
        SETCP0,
//        SETCP_SPECIAL,
        SETCPX
    )

    private fun tlbConstructors(vararg providers: TlbConstructorProvider<out AsmInstruction>) =
        providers.map { it.tlbConstructor() }
}